hmcts/ccd-case-print-service

config/custom-environment-variables.yaml
config/default.yaml
package.json
src/main/app.ts
src/main/routes/case-data-probate.ts
src/main/service/template-service.ts

PRO-2259
Allow probate service to supply dynamic templates per request from their api
```
[ ] Yes
[X ] No
```

PRO-2259: Dynamically fetch template from probate service

---

src/main/routes/case-data-probate.ts
src/main/service/template-service.ts

PRO-2259
Enable switchng of templates for sols and pa created cases
```
[ ] Yes
[X ] No
```

PRO-2259: switch templates for sols or pa

---

.nsprc
.travis.yml

Part of RDM-2000
```
[ ] Yes
[x] No
```

Add exception to vulnerability

---

package.json

RDM-2002 
This PR comments out sonar scan
```
[ ] Yes
[x] No
```

RDM-2002 Part 1

---

package.json

RDM-2002
Trying to get Jenkins build to pass
```
[ ] Yes
[x] No
```

Add more parameters to sonar-scan

---

Jenkinsfile_CNP

RDM-2002
Another stage in the journey
```
[ ] Yes
[x] No
```

Another bus

---

infrastructure/main.tf

N/A
Fix variable rename
```
[ ] Yes
[x] No
```

Fix variable rename

---

infrastructure/variables.tf

Add Probate Template url
```
[x] Yes
[ ] No
```

Add probate template url

---

infrastructure/saat.tfvars

Trial and error 1

---

Dockerfile
gulpfile.js
server.js
src/main/service/service-token-generator.ts

Fix issues found by codacy
```
[ ] Yes
[x] No
```

Fix qualit issues reported by codacy

---

infrastructure/saat.tfvars

[SKIP-PREVIEW] SAAT: Back to SIDAM

---

infrastructure/demo.tfvars

change probate template url

---

infrastructure/prod.tfvars

https://tools.hmcts.net/jira/browse/RDM-2358
Update prod URL for Probate template
```
[ ] Yes
[x] No
```

[SKIP-PREVIEW] RDM-2358 - Update prod URL for Probate template

---

Jenkinsfile_CNP

Yarn: clean cache, missing lodash error

---

infrastructure/aat.tfvars

https://tools.hmcts.net/jira/browse/RDM-2723
Update AAT config to use SIDAM
Comment out AAT config for tactical IDAM
```
[ ] Yes
[x] No
```

RDM-2723: Switch AAT to SIDAM

---

infrastructure/aat.tfvars

RDM-2723
Point AAT and Preview back to Tactical IDAM
```
[ ] Yes
[x] No
```

RDM-2723: Revert to Tactical IDAM

---

.snyk

This reverts commit df2630aa074944239aa753dd8a9b2847ce358649.
https://tools.hmcts.net/jira/browse/RDM-2861
```
[ ] Yes
[x] No
```

Revert "Snyk: remove patches which are possibly obsolete"

---

infrastructure/aat.tfvars

Reverts hmcts/ccd-case-print-service#76

RDM-2723: Switch to SIDAM

---

infrastructure/aat.tfvars

Reverts hmcts/ccd-case-print-service#89

RDM-2723: Switch to back to TIDAM

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/prod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/RDM-2484
Add properly named shared vault, migrate keys to use those, remove other
references.  Do everything except remove the vault itself.
```
[ ] Yes
[x] No
```

[PREVIEW] Migrate to Azure shared vault

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDM-2484
```
[ ] Yes
[x] No
```

Vault: remove old Hashi vault

---

infrastructure/sprod.tfvars

https://tools.hmcts.net/jira/browse/RDM-2635
```
[ ] Yes
[x] No
```

[PREVIEW] Keep sprod on per app ASP

---

src/main/routes/case-data-probate.ts

https://tools.hmcts.net/jira/browse/RDM-2961
Set charset UTF-8 for probate print case
```
[ ] Yes
[X] No
```

[PREVIEW] RDM-2961:add char encoding for probate print from template

---

.dockerignore
Dockerfile
Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RDM-3046
```
[ ] Yes
[x] No
```

Enable Docker build in CNP pipeline

---

infrastructure/prod.tfvars

https://tools.hmcts.net/jira/browse/RDM-3067
- Change login DNS from platform.hmcts.net to hmcts-access.service.gov.uk
```
[ ] Yes
[x] No
```

RDM-3067: Switch login DNS

---

.travis.yml

https://tools.hmcts.net/jira/browse/RDM-3093
```
[ ] Yes
[x] No
```

Add supported Node.js Travis versions

---

.travis.yml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDM-3592
```
[ ] Yes
[ ] No
```

Lock Terraform AzureRM to v1.19.0

---

infrastructure/main.tf
infrastructure/output.tf

https://tools.hmcts.net/jira/browse/RDM-2931
```
[ ] Yes
[ ] No
```

[PREVIEW] Use s2s vault

---

Dockerfile

Resolves CNP-1102
Hello, this PR adds the following enhancements:
improve the ordering of the docker image build layer
prepare for future ACR cache optimisations.
This is part of a general pipelines optimisations initiative and should not impact the current builds.
https://tools.hmcts.net/jira/browse/CNP-1102
Add some Dockerfile optimisations and layering to allow for faster Dockerbuild times.
```
[ ] Yes
[x] No
```

cnp-1102-Add Dockerfile optimisations

---

.travis.yml
Dockerfile
config/mocha.yaml
package.json

https://tools.hmcts.net/jira/browse/RDM-3320
```
[ ] Yes
[ ] No
```

Set minimum yarn version

---

src/main/routes/case-data-probate.ts
src/main/service/probate-man-service.ts
src/main/service/probate-man-template-service.ts
src/test/service/probate-man-service.spec.ts
src/test/service/probate-man-template-service.spec.ts

New endpoints to allow probate back office journey to view legacy case data in a HTML table.
```
[ ] Yes
[X] No
```

PRO-4391: Additions for probate legacy case viewer.

---

Dockerfile
Jenkinsfile_CNP
charts/ccd-case-print-service/Chart.yaml
charts/ccd-case-print-service/requirements.lock
charts/ccd-case-print-service/requirements.yaml
charts/ccd-case-print-service/values.aat.template.yaml
charts/ccd-case-print-service/values.template.yaml

https://tools.hmcts.net/jira/browse/RDM-3399
```
[ ] Yes
[ ] No
```

Implement Helm charts

---

.dockerignore
Dockerfile
Jenkinsfile_CNP
acb.tpl.yaml

https://tools.hmcts.net/jira/browse/CNP-1131
This PR leverages on layers re-use to reduce the the docker image build time in CI.
The image build is 3 min shorter.
[] Yes
[x] No

Use ACR cache optimisation in CI

---

package.json
yarn.lock

Bump snyk from 1.90.2 to 1.126.0

---

Dockerfile
infrastructure/main.tf
infrastructure/saat.tfvars
infrastructure/state.tf

Update Demo with latest Master

---

infrastructure/demo.tfvars

switch idam_api_url and authentication_web_url

---

infrastructure/demo.tfvars

SIDAM switch

---

infrastructure/saat.tfvars

switch sidam

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDM-4236
```
[ ] Yes
[ ] No
```

[PREVIEW] Move s2s vault to Terraform

---

Dockerfile
acb.tpl.yaml

RDM-5330-update ccd print service to use new docker registry url

---

charts/ccd-case-print-service/Chart.yaml
charts/ccd-case-print-service/requirements.lock
charts/ccd-case-print-service/requirements.yaml
charts/ccd-case-print-service/values.preview.template.yaml
charts/ccd-case-print-service/values.yaml

RDM-5309- Update Chart format for new AKS cluster

---

charts/ccd-case-print-service/Chart.yaml
charts/ccd-case-print-service/requirements.yaml

*Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x ] No
```

bump up base chart version

---

charts/ccd-case-print-service/Chart.yaml
charts/ccd-case-print-service/requirements.yaml

RDM-6596-bumped chart version, latest nodejs

---

charts/ccd-case-print-service/Chart.yaml

RDM-6674-updated chart, compatible with laetst HELM

---

aat/build.gradle
aat/src/aat/java/uk/gov/hmcts/ccd/printservice/befta/CasePrintServiceBeftaMain.java

upgrade befta fw version

---

Jenkinsfile_CNP

remove unused secrets

---

Jenkinsfile_CNP
aat/build.gradle

Rdm-7650 update befta version

---

Jenkinsfile_CNP
aat/build.gradle
aat/src/java/uk/gov/hmcts/ccd/printservice/befta/CasePrintServiceTestAutomationAdapter.java

enhance pipeline logic per build type

---

Jenkinsfile_CNP

Added data-store and DM-store baseURL
```
[ ] Yes
[X] No
```

Added data-store and DM_Store base URL

---

aat/src/resources/features/F-000/F-000.feature
aat/src/resources/features/F-000/S-000.td.json
aat/src/resources/features/F-023/F-023.feature
aat/src/resources/features/F-023/F-023_Case_Creation_Data_With_Document.td.json
aat/src/resources/features/F-023/F-023_Test_Data_Base.td.json
aat/src/resources/features/F-023/S-001.td.json
aat/src/resources/features/F-023/S-002.td.json
aat/src/resources/features/F-023/S-003.td.json
aat/src/resources/features/F-023/S-004.td.json
aat/src/resources/features/F-023/S-005.td.json
aat/src/resources/features/F-023/S-006.td.json
aat/src/resources/features/F-023/S-007.td.json
aat/src/resources/features/F-023/S-008.td.json
aat/src/resources/features/F-023/S-009.td.json
aat/src/resources/features/common/Case_Creation_Data_Base.td.json
aat/src/resources/features/common/Standard_Full_Case_Creation_Data.td.json
aat/src/resources/features/common/Standard_Full_Case_Data.td.json
aat/src/resources/features/common/Standard_Full_Case_Data_With_Document.td.json
aat/src/resources/features/common/Standard_Token_Creation_Data_For_Case_Creation.td.json

https://tools.hmcts.net/jira/browse/RDM-9283
Format Test JSON Data Files - Print Service
```
[ ] Yes
[x] No
```

RDM-9283 changes

---

charts/ccd-case-print-service/values.preview.template.yaml

correct wiring on preview

---

aat/build.gradle
aat/src/resources/features/F-000/F-000.feature
aat/src/resources/features/F-023/F-023.feature
aat/src/resources/features/F-023/F-023_Case_Creation_Data_With_Document.td.json
aat/src/resources/features/common/Standard_Token_Creation_Data_For_Case_Creation.td.json

https://tools.hmcts.net/jira/browse/RDM-9534
```
[ ] Yes
[X] No
```

Removing Health checks scenario as smoke tests

---

package.json

https://tools.hmcts.net/jira/browse/RDM-9805
```
[ ] Yes
[X] No
```

Removed redundant dependency audit - pipeline has it already

---

Jenkinsfile_CNP
charts/ccd-case-print-service/values.preview.template.yaml

[DO NOT MERGE] develop onto master

---

Jenkinsfile_CNP
charts/ccd-case-print-service/values.preview.template.yaml

update data store develop pr

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/RDM-10583
```
[ ] Yes
[X] No
```

Fix All Recent CVEs

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/RDM-11542
Advisory-1648 (Print Service)
```
[ ] Yes
[X] No
```

RDM-11542 Advisory-1648 (Print Service)

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/RDM-11729
```
[ ] Yes
[ ] No
```

RDM-11729: Upgrade befta to 6.13.0

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/RDM-11845
https://tools.hmcts.net/jira/browse/RDM-11930
bump up dependencies to resolve CVEs
```
[ ] Yes
[X] No
```

bump up dependencies to resolve CVEs

---

charts/ccd-case-print-service/Chart.yaml

https://tools.hmcts.net/jira/browse/RDM-12054
Upgrade Base Chart Versions (Java & Nodejs)
```
[ ] Yes
[X] No
```

RDM-12054 Upgrade Base Chart Versions (Java & Nodejs)

---

.github/workflows/scheduled-dummy-commit.yml

RDM-11603, no develop branch protection on this repo
```
[ ] Yes
[x] No
```

Create scheduled-dummy-commit.yml RDM-11603

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/RDM-9765
Bump up BEFTA Fw version for RDM-9765.
```
[ ] Yes
[X] No
```

RDM-9765 Added jit pack and befta code changes

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/CCD-1041
Fix Advisory - 1673 in case Print service includes All recent CVE fixes
```
[ ] Yes
[x] No
```

CCD-1041 Fix Print Service CVE issues

---

.gitignore
Jenkinsfile_nightly
aat/build.gradle
aat/config/fortify-client.properties
aat/gradle/wrapper/gradle-wrapper.properties
package.json

https://tools.hmcts.net/jira/browse/CCD-1572
Integrated Fortify Scan into Nightly Pipelines
```
[ ] Yes
[x] No
```

CCD-1572: Integrate Fortify Scan into Nightly Pipelines

---

package.json
yarn.lock

Resolve CVE-2021-23406
```
[ ] Yes
[x] No
```

CFTS-1028 Resolve CVE-2021-23406

---

package.json

https://tools.hmcts.net/jira/browse/CCD-2344
Resolve build issues
```
[ ] Yes
[x] No
```

update to resolve build failure

---

.travis.yml
Dockerfile
gulpfile.js
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/CCD-2344
Update NodeJS library version
```
[ ] Yes
[x] No
```

update nodejs engine version to resolve build failure

---

package.json
yarn.lock

Reverts hmcts/ccd-case-print-service#373

Revert "Origin/ccd 2792 fix remaining dependant bot issue"

---

Jenkinsfile_CNP
charts/ccd-case-print-service/values.preview.template.yaml

CCD-3639 (https://tools.hmcts.net/jira/browse/CCD-3639)
Changed values of DEFINITION_STORE_URL_BASE and CCD_DATA_STORE_API_BASE_URL variables used for preview environment in Jenkinsfile_CNP to use https instead of http.
Changed value of CASE_DATA_STORE in values.preview.template.yaml; replaced ".service.core-compute-preview.internal" with "-java".
```
[ ] Yes
[x] No
```

CCD-3639: Fix preview deployment issues

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/CCD-3802
Update to fortify-client version
```
[ ] Yes
[ x] No
```

CCD-3802 Update to fortify-client version

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/CCD-4338
Upgraded packages to resolve dependabot errors
```
[ ] Yes
[X] No
```

CCD-4338 : Upgraded packages to resolve dependabot errors

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/CCD-4408
```
[ ] Yes
[ ] No
```

update befta-fw version to 8.7.11

---

src/main/util/fetch.ts

https://tools.hmcts.net/jira/browse/CCD-4712
CCD-4712 : fix for sonar gate failure
```
[ ] Yes
[X] No
```

CCD-4712 : fix for sonar gate failure

---

src/main/util/fetch.ts

https://tools.hmcts.net/jira/browse/CCD-4712
Test sonar fix
```
[ ] Yes
[ ] No
```

CCD-4712 : test sonar fix

---

package.json

https://tools.hmcts.net/jira/browse/CCD-966
Fix spectacularly old and well known issue.
```
[ ] Yes
[x] No
```

CCD-966 - Take that, Probate Man

---

aat/build.gradle

https://tools.hmcts.net/jira/browse/CME-311
downgrade ccd-test-definitions to 7.24.2 (latest tagged)
```
[ ] Yes
[X] No
```

CME-311: downgrade ccd-test-definitions to 7.24.2 (latest tagged)

---

package.json

NA
package-manager
```
[ ] Yes
[X] No
```

remove package-manager

---

charts/ccd-case-print-service/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```

CCD-6193 update base chart version
